import { createServer } from 'node:http';
import { createReadStream, existsSync, statSync } from 'node:fs';
import { extname, join, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const { Pool } = pg;

const root = resolve(fileURLToPath(new URL('.', import.meta.url)));
const port = Number(process.env.PORT || 3000);
const databaseUrl = process.env.DATABASE_URL || '';
const betaPool = databaseUrl
  ? new Pool({ connectionString: databaseUrl, max: 5, connectionTimeoutMillis: 5000, idleTimeoutMillis: 30000 })
  : null;
let betaSchemaReady;
let betaSchemaPromise;
const contentTypes = new Map([
  ['.css', 'text/css; charset=utf-8'],
  ['.html', 'text/html; charset=utf-8'],
  ['.ico', 'image/x-icon'],
  ['.jpeg', 'image/jpeg'],
  ['.jpg', 'image/jpeg'],
  ['.js', 'text/javascript; charset=utf-8'],
  ['.json', 'application/json; charset=utf-8'],
  ['.png', 'image/png'],
  ['.svg', 'image/svg+xml'],
  ['.txt', 'text/plain; charset=utf-8'],
  ['.webp', 'image/webp'],
  ['.xml', 'application/xml; charset=utf-8'],
]);
const publicFiles = new Set([
  '/404.html',
  '/about.html',
  '/app.js',
  '/assets/app-concept.webp',
  '/assets/app-showcase.webp',
  '/assets/cta-concept.webp',
  '/assets/cta-dog-phone.webp',
  '/assets/gift.webp',
  '/assets/hero-cat.webp',
  '/assets/hero-concept.webp',
  '/assets/how-concept.webp',
  '/assets/pet-miss.webp',
  '/assets/pet-now.webp',
  '/assets/step-companion.webp',
  '/assets/step-photo.webp',
  '/assets/step-play.webp',
  '/assets/stories-concept.webp',
  '/assets/story-golden-hour.webp',
  '/assets/uses-concept.webp',
  '/faq.html',
  '/beta.html',
  '/apple-touch-icon.png',
  '/favicon-32.png',
  '/favicon.ico',
  '/favicon.svg',
  '/how-it-works.html',
  '/index.html',
  '/privacy.html',
  '/robots.txt',
  '/sitemap.xml',
  '/stories.html',
  '/styles.css',
  '/terms.html',
]);

function setCommonHeaders(response) {
  response.setHeader('X-Content-Type-Options', 'nosniff');
  response.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');
  response.setHeader('X-Frame-Options', 'DENY');
  response.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
  response.setHeader(
    'Content-Security-Policy',
    "default-src 'self'; img-src 'self' data:; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests",
  );
}

function sendNotFound(response, method) {
  const page = join(root, '404.html');
  response.statusCode = 404;
  response.setHeader('Content-Type', 'text/html; charset=utf-8');
  response.setHeader('Cache-Control', 'no-store');
  if (method === 'HEAD') {
    response.end();
    return;
  }
  createReadStream(page).pipe(response);
}

function sendJson(response, statusCode, body) {
  response.statusCode = statusCode;
  response.setHeader('Content-Type', 'application/json; charset=utf-8');
  response.setHeader('Cache-Control', 'no-store');
  response.end(JSON.stringify(body));
}

async function ensureBetaSchema() {
  if (!betaPool) return false;
  if (betaSchemaReady) return true;
  if (!betaSchemaPromise) {
    betaSchemaPromise = betaPool.query(`
      CREATE TABLE IF NOT EXISTS beta_signups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        consented_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        consent_version TEXT NOT NULL,
        source TEXT NOT NULL DEFAULT 'worntag-beta-page'
      )
    `).then(() => {
      betaSchemaReady = true;
      return true;
    }).catch(() => {
      betaSchemaPromise = null;
      return false;
    });
  }
  return betaSchemaPromise;
}

function sameOrigin(request) {
  const origin = request.headers.origin;
  if (!origin) return false;
  try {
    return new URL(origin).host.toLowerCase() === String(request.headers.host || '').toLowerCase();
  } catch {
    return false;
  }
}

async function readJsonBody(request, maxBytes = 4096) {
  const chunks = [];
  let length = 0;
  for await (const chunk of request) {
    length += chunk.length;
    if (length > maxBytes) {
      const error = new Error('Request body too large');
      error.statusCode = 413;
      throw error;
    }
    chunks.push(chunk);
  }
  try {
    return JSON.parse(Buffer.concat(chunks).toString('utf8'));
  } catch {
    const error = new Error('Invalid JSON');
    error.statusCode = 400;
    throw error;
  }
}

function normalizeEmail(value) {
  if (typeof value !== 'string') return null;
  const email = value.trim().normalize('NFKC').toLowerCase();
  if (email.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return null;
  return email;
}

async function handleBetaSignup(request, response) {
  if (request.method !== 'POST') {
    sendJson(response, 405, { error: 'Method not allowed.' });
    return;
  }
  if (!sameOrigin(request)) {
    sendJson(response, 403, { error: 'Request could not be accepted.' });
    return;
  }
  if (!String(request.headers['content-type'] || '').toLowerCase().startsWith('application/json')) {
    sendJson(response, 415, { error: 'Please submit the form normally.' });
    return;
  }

  let body;
  try {
    body = await readJsonBody(request);
  } catch (error) {
    sendJson(response, error.statusCode || 400, { error: error.statusCode === 413 ? 'That request is too large.' : 'Please check the form and try again.' });
    return;
  }

  const email = normalizeEmail(body.email);
  if (body.website) {
    sendJson(response, 202, { ok: true, message: 'If beta sign-ups are open, your request has been received.' });
    return;
  }
  if (!email || body.consent !== true) {
    sendJson(response, 400, { error: 'Enter a valid email and tick the consent box.' });
    return;
  }
  if (!await ensureBetaSchema()) {
    sendJson(response, 503, { error: 'Beta sign-ups are not open yet. Please try again later.' });
    return;
  }

  try {
    await betaPool.query(
      `INSERT INTO beta_signups (email, consent_version) VALUES ($1, $2) ON CONFLICT (email) DO NOTHING`,
      [email, 'beta-invite-2026-09-v1'],
    );
    sendJson(response, 201, { ok: true, message: 'Thanks — your email is on the WornTag beta invite list.' });
  } catch {
    sendJson(response, 503, { error: 'We could not save that just now. Please try again later.' });
  }
}

async function handleBetaRemoval(request, response) {
  if (request.method !== 'POST') {
    sendJson(response, 405, { error: 'Method not allowed.' });
    return;
  }
  if (!sameOrigin(request)) {
    sendJson(response, 403, { error: 'Request could not be accepted.' });
    return;
  }
  if (!String(request.headers['content-type'] || '').toLowerCase().startsWith('application/json')) {
    sendJson(response, 415, { error: 'Please submit the form normally.' });
    return;
  }
  let body;
  try {
    body = await readJsonBody(request);
  } catch (error) {
    sendJson(response, error.statusCode || 400, { error: 'Please check the form and try again.' });
    return;
  }
  const email = normalizeEmail(body.email);
  if (!email) {
    sendJson(response, 400, { error: 'Enter the email address you used to join.' });
    return;
  }
  if (!await ensureBetaSchema()) {
    sendJson(response, 503, { error: 'Beta sign-ups are not open yet.' });
    return;
  }
  try {
    await betaPool.query('DELETE FROM beta_signups WHERE email = $1', [email]);
    sendJson(response, 200, { ok: true, message: 'If that address was on the list, it has been removed.' });
  } catch {
    sendJson(response, 503, { error: 'We could not remove that just now. Please try again later.' });
  }
}

const server = createServer((request, response) => {
  setCommonHeaders(response);

  let requestPath;
  let requestUrl;
  try {
    requestUrl = new URL(request.url, 'http://localhost');
    requestPath = requestUrl.pathname;
  } catch {
    sendNotFound(response, request.method);
    return;
  }

  const host = String(request.headers.host || '').toLowerCase().replace(/:443$/, '');
  const canonicalPath = requestPath === '/index.html' ? '/' : requestUrl.pathname;
  if ((request.method === 'GET' || request.method === 'HEAD')
    && (host === 'www.worntag.com' || requestPath === '/index.html')) {
    response.statusCode = 301;
    response.setHeader('Location', `https://worntag.com${canonicalPath}${requestUrl.search}`);
    response.setHeader('Cache-Control', 'public, max-age=3600');
    response.end();
    return;
  }

  if (requestPath === '/health') {
    response.statusCode = 200;
    response.setHeader('Content-Type', 'application/json; charset=utf-8');
    response.setHeader('Cache-Control', 'no-store');
    response.end(request.method === 'HEAD' ? undefined : JSON.stringify({ status: 'ok' }));
    return;
  }

  if (requestPath === '/api/beta-signups/status' && request.method === 'GET') {
    ensureBetaSchema().then((open) => sendJson(response, 200, { open }));
    return;
  }
  if (requestPath === '/api/beta-signups') {
    handleBetaSignup(request, response);
    return;
  }
  if (requestPath === '/api/beta-signups/remove') {
    handleBetaRemoval(request, response);
    return;
  }

  if (request.method !== 'GET' && request.method !== 'HEAD') {
    response.statusCode = 405;
    response.setHeader('Allow', 'GET, HEAD');
    response.end();
    return;
  }

  let pathname;
  try {
    pathname = decodeURIComponent(requestPath);
  } catch {
    sendNotFound(response, request.method);
    return;
  }

  if (pathname === '/') pathname = '/index.html';
  if (!publicFiles.has(pathname)) {
    sendNotFound(response, request.method);
    return;
  }
  const target = resolve(root, `.${pathname}`);
  if (target !== root && !target.startsWith(`${root}${sep}`)) {
    sendNotFound(response, request.method);
    return;
  }
  if (!existsSync(target) || !statSync(target).isFile()) {
    sendNotFound(response, request.method);
    return;
  }

  response.statusCode = 200;
  response.setHeader('Content-Type', contentTypes.get(extname(target).toLowerCase()) || 'application/octet-stream');
  const extension = extname(target).toLowerCase();
  response.setHeader('Cache-Control', ['.html', '.css', '.js'].includes(extension) ? 'no-cache' : 'public, max-age=86400');
  if (request.method === 'HEAD') {
    response.end();
    return;
  }
  createReadStream(target).pipe(response);
});

server.listen(port, '0.0.0.0', () => {
  process.stdout.write(`WornTag site listening on ${port}\n`);
});
